######################################################
####         EVENT MANAGEMENT API TESTING         ####
######################################################


### Base URL and port
@port=37391

### Local test
@api_base_url = http://localhost:{{port}}/odata/v4/management/

### Uncomment this line below to test deployed application
###@api_base_url = https://2fda7038trial-trial-spnpjyiq-events-man-event-managemen5a33b8dd.cfapps.us10-001.hana.ondemand.com/odata/v4/management/



##############
### EVENTS ###
##############

### Get all events
GET {{api_base_url}}Events
Accept: application/json

### Create a new event
POST {{api_base_url}}Events
Content-Type: application/json

{
  "Name": "Tech Conference 2024",
  "StartDate": "2024-07-01",
  "EndDate": "2024-07-03",
  "Location": "New York City",
  "Description": "Annual Technology Conference",
  "IsActive": true,
  "IsCancelled": false,
  "CancellationReason": null
}

### Update an event
PATCH {{api_base_url}}Events(1)
Content-Type: application/json

{
  "Description": "Updated description for Tech Conference 2024"
}

### Delete an event
DELETE {{api_base_url}}Events(1)



####################
### PARTICIPANTS ###
####################

### Get all participants
GET {{api_base_url}}Participants
Accept: application/json

### Create a participant
POST {{api_base_url}}Participants
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "johndoe@xample.com",
  "Phone": "123456789",
  "BusinessPartnerID": "1000000"
}

### Update a participant (BusinessPartnerID cannot be changed)
PATCH {{api_base_url}}Participants(1)
Content-Type: application/json

{
  "BusinessPartnerID": "987654321"
}

### Delete a participant
DELETE {{api_base_url}}Participants(1)



####################
### CUSTOM LOGIC ###
####################

### Fetch Participant Details
GET {{api_base_url}}fetchParticipantDetails(ParticipantID=2)
Accept: application/json


### Register a participant for an event
POST {{api_base_url}}registerParticipant
Content-Type: application/json

{
  "eventID": 2,
  "participantID": 2
}

### Cancel an event
POST {{api_base_url}}cancelEvent
Content-Type: application/json

{
  "eventID": 2,
  "reason": "Weather conditions"
}

### Reopen an event
POST {{api_base_url}}reopenEvent
Content-Type: application/json

{
  "eventID": 2
}

### Retrieve participants for a specific event
GET {{api_base_url}}getEventParticipants(eventID=2)
Accept: application/json



########################################
### Wrong information to test errors ###
########################################


### Create a participant with existent email 
### Use after created a participant before
POST {{api_base_url}}Participants
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "johndoe@xample.com",
  "Phone": "123456789",
  "BusinessPartnerID": "1000000"
}


### Update a participant changing BusinessPartnerID
PATCH {{api_base_url}}Participants(1)
Content-Type: application/json

{
  "FirstName": "Charles",
  "LastName": "Doe",
  "Email": "johndoe@xample.com",
  "Phone": "123456789",
  "BusinessPartnerID": "1000200"
}

### Fetch Participant Details wiht an id that does not exist
GET {{api_base_url}}fetchParticipantDetails(ParticipantID=1)
Accept: application/json

### Register a participant for an event that does not exist
POST {{api_base_url}}registerParticipant
Content-Type: application/json

{
  "eventID": 1,
  "participantID": 2
}

### Cancel an event tahat does not exist
POST {{api_base_url}}cancelEvent
Content-Type: application/json

{
  "eventID": 2,
  "reason": "Weather conditions"
}

### Reopen an event that does not exist
POST {{api_base_url}}reopenEvent
Content-Type: application/json

{
  "eventID": 2
}


########################################
###      Extra data for adding       ###
########################################

### Participants
###
POST {{api_base_url}}Participants
Content-Type: application/json

{
  "FirstName": "Linda",
  "LastName": "Johnson",
  "Email": "linda.johnson@email.com",
  "Phone": "902709987",
  "BusinessPartnerID": "1000000"
}

###
POST {{api_base_url}}Participants
Content-Type: application/json

{
  "FirstName": "Michael",
  "LastName": "Jones",
  "Email": "michael.jones@email.com",
  "Phone": "813039790",
  "BusinessPartnerID": "1000000"
}

###
POST {{api_base_url}}Participants
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Wilson",
  "Email": "james.wilson@email.com",
  "Phone": "698292056",
  "BusinessPartnerID": "1000000"
}


### Events
###
POST {{api_base_url}}Events
Content-Type: application/json

{
  "Name": "Marketing Summit",
  "StartDate": "2024-07-01",
  "EndDate": "2024-07-03",
  "Location": "San Francisco",
  "Description": "A summit dedicated to the world of e-commerce",
  "IsActive": true,
  "IsCancelled": false,
  "CancellationReason": null
}

###
POST {{api_base_url}}Events
Content-Type: application/json

{
  "Name": "International HR Forum",
  "StartDate": "2024-07-01",
  "EndDate": "2024-07-03",
  "Location": "Barcelona",
  "Description": "A conference on media and entertainment technologies",
  "IsActive": true,
  "IsCancelled": false,
  "CancellationReason": null
}

###
POST {{api_base_url}}Events
Content-Type: application/json

{
  "Name": "Virtual Reality Development Expo",
  "StartDate": "2024-07-01",
  "EndDate": "2024-07-03",
  "Location": "Vancouver",
  "Description": "An expo focused on VR and AR development",
  "IsActive": true,
  "IsCancelled": false,
  "CancellationReason": null
}