######################################################
####         EVENT MANAGEMENT API TESTING         ####
######################################################


### Base URL and port
@port=4004

### Local test
@api_base_url = http://localhost:{{port}}/odata/v4/management/

### Uncomment this line below to test deployed application
###@api_base_url = https://2fda7038trial-trial-spnpjyiq-events-man-event-managemen5a33b8dd.cfapps.us10-001.hana.ondemand.com/odata/v4/management/



##############
### EVENTS ###
##############

### Get all events
GET {{api_base_url}}Events
Accept: application/json

### Create a new event
POST {{api_base_url}}Events
Content-Type: application/json

{
  "Name": "Tech Conference 2024",
  "StartDate": "2024-07-01",
  "EndDate": "2024-07-03",
  "Location": "New York City",
  "Description": "Annual Technology Conference",
  "IsActive": true,
  "IsCancelled": false,
  "CancellationReason": null
}

### Update an event
PATCH {{api_base_url}}Events(1)
Content-Type: application/json

{
  "Description": "Updated description for Tech Conference 2024"
}

### Delete an event
DELETE {{api_base_url}}Events(1)



####################
### PARTICIPANTS ###
####################

### Get all participants
GET {{api_base_url}}Participants
Accept: application/json

### Create a participant
POST {{api_base_url}}Participants
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "johndoe@xample.com",
  "Phone": "123456789",
  "BusinessPartnerID": "1000000"
}

### Update a participant (BusinessPartnerID cannot be changed)
PATCH {{api_base_url}}Participants(1)
Content-Type: application/json

{
  "BusinessPartnerID": "987654321"
}

### Delete a participant
DELETE {{api_base_url}}Participants(37)



####################
### CUSTOM LOGIC ###
####################

### Fetch Participant Details
GET {{api_base_url}}fetchParticipantDetails(ParticipantID=1)
Accept: application/json


### Register a participant for an event
POST {{api_base_url}}registerParticipant
Content-Type: application/json

{
  "eventID": 1,
  "participantID": 2
}

### Cancel an event
POST {{api_base_url}}cancelEvent
Content-Type: application/json

{
  "eventID": 2,
  "reason": "Weather conditions"
}

### Reopen an event
POST {{api_base_url}}reopenEvent
Content-Type: application/json

{
  "eventID": 2
}

### Retrieve participants for a specific event
GET {{api_base_url}}getEventParticipants(eventID=1)
Accept: application/json



########################################
### Worng information to test errors ###
########################################